name: game_box
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.2
  cupertino_icons: 1.0.2
  introduction_screen: 3.1.11
  audioplayers: 5.2.1
  flutter_bloc: 8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  equatable: ^2.0.5

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/audio/

   